"""Roles, authority matrix (artifact -> roles allowed to approve) and CODEOWNERS generation."""
from __future__ import annotations

from pathlib import Path

from .core import Report, paths

CODEOWNERS_HEADER = "# Generated by `sdlc codeowners` from .harness/roster.toml. Do not edit by hand."


def roles(cfg: dict) -> dict[str, list[str]]:
    return {name: spec.get("members", []) for name, spec in cfg["_roster"].get("roles", {}).items()}


def approver_roles(cfg: dict, artifact_key: str) -> list[str]:
    return cfg["_roster"].get("authority", {}).get(artifact_key, [])


def artifact_key(cfg: dict, artifact_path: str) -> str:
    """Authority key for a repo-relative artifact path: ADRs share the key `adr`."""
    adr_dir = paths(cfg)["adr"].rstrip("/") + "/"
    return "adr" if artifact_path.startswith(adr_dir) else artifact_path.rsplit("/", 1)[-1]


def is_team(member: str) -> bool:
    return member.startswith("@") and "/" in member


def local_membership(cfg: dict, role: str, user: str) -> bool | None:
    """True/False when decidable from the roster alone; None when it depends on a platform team."""
    members = roles(cfg).get(role, [])
    if user in (m.lstrip("@") for m in members if not is_team(m)):
        return True
    return None if any(is_team(m) for m in members) else False


def settings(cfg: dict) -> dict:
    s = cfg["_roster"].get("settings", {})
    return {"platform": s.get("platform", "github"), "separation_of_duties": s.get("separation_of_duties", True)}


def check_roster(cfg: dict, strict: bool) -> Report:
    report = Report()
    level = report.error if strict else report.warn
    if not cfg["_roster"]:
        level("no .harness/roster.toml: approvals cannot be attributed to roles")
        return report
    defined = roles(cfg)
    for key, allowed in cfg["_roster"].get("authority", {}).items():
        for role in allowed:
            if role not in defined:
                report.error(f"roster: authority '{key}' references undefined role '{role}'")
            elif not defined[role]:
                level(f"roster: role '{role}' (approves '{key}') has no members")
    return report


def render_codeowners(cfg: dict) -> tuple[str, Report]:
    report = Report()
    p = paths(cfg)
    defined = roles(cfg)
    entries: list[tuple[str, list[str]]] = []

    def owners(role_names: list[str], label: str) -> list[str]:
        out = []
        for r in role_names:
            if not defined.get(r):
                report.warn(f"codeowners: role '{r}' for {label} has no members; skipped")
            out += ["@" + m.lstrip("@") for m in defined.get(r, [])]
        return list(dict.fromkeys(out))

    # Generic ownership first: in CODEOWNERS the last matching pattern wins.
    for pattern, role_names in cfg["_roster"].get("codeowners", {}).items():
        if o := owners(role_names, pattern):
            entries.append((pattern, o))
    authority = cfg["_roster"].get("authority", {})
    all_approvers: list[str] = []
    for key, allowed in authority.items():
        pattern = f"/{p['adr'].strip('/')}/" if key == "adr" else f"/{p['changes'].strip('/')}/*/{key}"
        if o := owners(allowed, key):
            entries.append((pattern, o))
            all_approvers += o
    if all_approvers:
        entries.append((f"/{p['changes'].strip('/')}/*/approvals.toml", list(dict.fromkeys(all_approvers))))
    width = max((len(pat) for pat, _ in entries), default=0) + 2
    lines = [CODEOWNERS_HEADER, "# Later rules take precedence over earlier ones.", ""]
    lines += [f"{pat.ljust(width)}{' '.join(o)}" for pat, o in entries]
    return "\n".join(lines) + "\n", report


def codeowners_path(root: Path, cfg: dict) -> Path:
    return root / (".github/CODEOWNERS" if settings(cfg)["platform"] == "github" else ".gitlab/CODEOWNERS")
