"""Command-line interface."""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

from . import (adapters, architecture, audit, authority, changes, contracts, evidence, installer, platform,
               receipts, skills, tdd)
from .core import PHASES, PROFILES, RISKS, TYPES, VERSION, Report, git, load_config, paths

CONVENTIONAL_RE = re.compile(
    r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?!?: .+"
)
ADR_FILE_RE = re.compile(r"^\d{4}-[a-z0-9]+(-[a-z0-9]+)*\.md$")
ADR_STATUS_RE = re.compile(r"^\*\*Status:\*\*\s*(Proposed|Accepted|Rejected|Deprecated|Superseded by \d{4})\s*$", re.M)


def sensor_level(cfg: dict, name: str, default: str = "error") -> str:
    return cfg["_profile"].get("sensors", {}).get(name, default)


def apply_level(report: Report, level: str) -> Report:
    if level == "off":
        return Report()
    if level == "warn":
        return Report(errors=[], warnings=report.warnings + report.errors)
    return report


def run_sensors(root: Path, cfg: dict, base: str | None) -> Report:
    report = Report()
    report.extend(apply_level(architecture.check(root), sensor_level(cfg, "architecture")))
    if base:
        report.extend(apply_level(tdd.check_test_first(root, cfg, base), sensor_level(cfg, "test_first", "warn")))
        report.extend(apply_level(tdd.check_weakened_tests(root, cfg, base), sensor_level(cfg, "weakened_tests")))
        report.extend(apply_level(contracts.check(root, cfg, base), sensor_level(cfg, "contracts")))
    return report


def run_check(root: Path, only_change: str | None = None, base: str | None = None) -> Report:
    cfg = load_config(root)
    p = paths(cfg)
    report = Report()
    if only_change is None:
        skills_report, found = skills.check_skills(root, p["skills"])
        report.extend(skills_report)
        report.extend(skills.check_agents_md(root, cfg, found))
        report.extend(check_adr_files(root, p["adr"]))
        report.extend(adapters.check(root, cfg))
        report.extend(authority.check_roster(cfg, strict=False))
        report.extend(run_sensors(root, cfg, base))
    base_dir = root / p["changes"]
    if only_change:
        report.extend(changes.check_change(root, changes.change_dir(root, cfg, only_change), cfg))
    elif base_dir.is_dir():
        for d in sorted(x for x in base_dir.iterdir() if x.is_dir()):
            report.extend(changes.check_change(root, d, cfg))
            if base and (d / audit.AUDIT_FILE).exists():
                report.extend(audit.verify_append_only(root, d / audit.AUDIT_FILE, base))
    return report


def check_adr_files(root: Path, adr_dir: str) -> Report:
    report = Report()
    base = root / adr_dir
    if not base.is_dir():
        return report
    for f in sorted(base.glob("*.md")):
        if f.name.lower() in ("readme.md", "template.md"):
            continue
        rel = f.relative_to(root)
        if not ADR_FILE_RE.match(f.name):
            report.error(f"{rel}: ADR filename must be NNNN-kebab-title.md")
        if not ADR_STATUS_RE.search(f.read_text(encoding="utf-8")):
            report.error(f"{rel}: missing or invalid '**Status:**' line")
    return report


def cmd_commit_msg(root: Path, file: str) -> int:
    cfg = load_config(root)
    msg = Path(file).read_text(encoding="utf-8")
    lines = [line for line in msg.splitlines() if not line.startswith("#")]
    report = Report()
    subject = lines[0] if lines else ""
    if not subject.startswith(("Merge ", "Revert ")) and not CONVENTIONAL_RE.match(subject):
        report.error("subject must follow Conventional Commits: type(scope): summary")
    for trailer in cfg["_profile"].get("commits", {}).get("require_trailers", []):
        if not re.search(rf"^{re.escape(trailer)}: .+$", msg, re.M):
            report.error(f"missing required trailer '{trailer}: <value>' (use 'none' if not applicable)")
    return report.print() if report.errors else 0


def cmd_codeowners(root: Path, check_only: bool) -> int:
    cfg = load_config(root)
    content, report = authority.render_codeowners(cfg)
    target = authority.codeowners_path(root, cfg)
    current = target.read_text(encoding="utf-8") if target.exists() else ""
    if check_only:
        if current != content:
            report.error(f"{target.relative_to(root)} is out of date; run `sdlc codeowners`")
        return report.print()
    if current and not current.startswith(authority.CODEOWNERS_HEADER):
        report.error(f"{target.relative_to(root)} was not generated by sdlc; move custom rules to roster [codeowners]")
        return report.print()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {target.relative_to(root)}")
    return report.print()


def cmd_doctor(root: Path) -> int:
    cfg = load_config(root)
    regulated = cfg.get("harness", {}).get("profile") == "regulated"
    report = Report()
    strict = report.error if regulated else report.warn
    if sys.version_info < (3, 11):
        report.error("Python >= 3.11 required")
    if git(root, "config", "--get", "core.hooksPath", check=False) != ".harness/hooks":
        report.warn("git hooks not installed; run `sdlc hooks` (CI remains the authoritative gate)")
    if not ((root / ".github/workflows/sdlc-gates.yml").exists() or (root / ".gitlab-ci.sdlc.yml").exists()):
        strict("no CI gate found; local hooks can be bypassed")
    codeowners = authority.codeowners_path(root, cfg)
    if not codeowners.exists():
        strict(f"no {codeowners.relative_to(root)}: run `sdlc codeowners` so the platform enforces approvals")
    elif authority.render_codeowners(cfg)[0] != codeowners.read_text(encoding="utf-8"):
        report.warn(f"{codeowners.relative_to(root)} differs from roster; run `sdlc codeowners`")
    report.extend(authority.check_roster(cfg, strict=regulated))
    if (installed := cfg.get("harness", {}).get("version")) and installed != VERSION:
        report.warn(f"harness.toml version {installed} != CLI {VERSION}")
    report.extend(run_check(root))
    return report.print()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="sdlc", description="Agent-agnostic SDLC harness")
    parser.add_argument("--root", default=".", help="repository root (default: .)")
    parser.add_argument("--version", action="version", version=VERSION)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("init", help="install the harness into a repository")
    p.add_argument("target")
    p.add_argument("--profile", choices=PROFILES, default="standard")
    p.add_argument("--agents", default="claude-code,codex,copilot,cursor,gemini-cli")
    p.add_argument("--mode", choices=["symlink", "copy"], default="symlink")
    p.add_argument("--ci", choices=["github", "gitlab", "none"], default="github")

    sub.add_parser("sync", help="regenerate AGENTS.md skills index and agent adapters")

    p = sub.add_parser("check", help="validate skills, ADRs, adapters, roster and change gates")
    p.add_argument("--change", help="only validate this change id")
    p.add_argument("--base", help="git ref; also enforce append-only audit logs against it (CI)")

    p = sub.add_parser("new", help="start a change record")
    p.add_argument("type", choices=TYPES)
    p.add_argument("slug")
    p.add_argument("--risk", choices=RISKS, default="medium")
    p.add_argument("--no-ai", dest="ai_assisted", action="store_false")

    p = sub.add_parser("phase", help="move a change to the next phase if its gate passes")
    p.add_argument("change")
    p.add_argument("phase", choices=PHASES)

    p = sub.add_parser("approve", help="record a human approval receipt for an artifact")
    p.add_argument("change")
    p.add_argument("artifact", help="file in the change record (spec.md) or repo-relative path (docs/adr/0001-x.md)")
    p.add_argument("--as", dest="approver", required=True, help="your platform username")
    p.add_argument("--role", required=True)

    p = sub.add_parser("approvals", help="verify approval receipts against GitHub/GitLab (CI)")
    p.add_argument("action", choices=["verify"])
    p.add_argument("--platform", choices=["github", "gitlab"])
    p.add_argument("--base", required=True, help="base ref of the pull/merge request")
    p.add_argument("--pr", type=int, help="pull/merge request number (default: from CI environment)")

    p = sub.add_parser("audit", help="verify audit log hash chains")
    p.add_argument("action", choices=["verify"])
    p.add_argument("--base", help="also enforce append-only against this git ref")

    p = sub.add_parser("tdd", help="test-first ordering and weakened tests over base..HEAD")
    p.add_argument("--base", required=True)

    sub.add_parser("arch", help="check layer dependencies from .harness/architecture.toml")

    p = sub.add_parser("contracts", help="detect breaking changes in API contracts against a base ref")
    p.add_argument("--base", required=True)

    p = sub.add_parser("evidence", help="enforce policy on SARIF findings and CycloneDX SBOMs")
    p.add_argument("action", choices=["check"])
    p.add_argument("--dir", help="evidence directory (default: [evidence] dir or sdlc-evidence)")
    p.add_argument("--require", help="comma-separated evidence kinds, overriding the profile (e.g. sbom)")

    p = sub.add_parser("codeowners", help="generate CODEOWNERS from .harness/roster.toml")
    p.add_argument("--check", action="store_true", help="fail if CODEOWNERS is out of date")

    p = sub.add_parser("commit-msg", help="validate a commit message file")
    p.add_argument("file")

    sub.add_parser("hooks", help="enable the harness git hooks")
    sub.add_parser("doctor", help="check controls and configuration")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.root).resolve()
    match args.command:
        case "init":
            agents = [a.strip() for a in args.agents.split(",") if a.strip()]
            return installer.init(Path(args.target).resolve(), args.profile, agents, args.mode, args.ci)
        case "sync":
            return installer.sync(root)
        case "check":
            return run_check(root, args.change, args.base).print()
        case "new":
            return changes.new(root, args.type, args.slug, args.risk, args.ai_assisted)
        case "phase":
            return changes.phase(root, args.change, args.phase)
        case "approve":
            cfg = load_config(root)
            d = changes.change_dir(root, cfg, args.change)
            artifact = args.artifact if "/" in args.artifact else f"{d.relative_to(root).as_posix()}/{args.artifact}"
            return receipts.approve(root, cfg, d, artifact, args.approver, args.role)
        case "approvals":
            cfg = load_config(root)
            name = args.platform or authority.settings(cfg)["platform"]
            client = platform.client_from_env(root, name, args.pr)
            return platform.verify(root, client, args.base).print()
        case "audit":
            cfg = load_config(root)
            report = Report()
            for log in sorted((root / paths(cfg)["changes"]).glob(f"*/{audit.AUDIT_FILE}")):
                report.extend(audit.verify_chain(root, log))
                if args.base:
                    report.extend(audit.verify_append_only(root, log, args.base))
            return report.print()
        case "tdd":
            cfg = load_config(root)
            report = tdd.check_test_first(root, cfg, args.base).extend(tdd.check_weakened_tests(root, cfg, args.base))
            return report.print()
        case "arch":
            load_config(root)
            return architecture.check(root).print()
        case "contracts":
            return contracts.check(root, load_config(root), args.base).print()
        case "evidence":
            require = [k for k in args.require.split(",") if k] if args.require is not None else None
            return evidence.check(root, load_config(root), args.dir, require).print()
        case "codeowners":
            return cmd_codeowners(root, args.check)
        case "commit-msg":
            return cmd_commit_msg(root, args.file)
        case "hooks":
            subprocess.run(["git", "config", "core.hooksPath", ".harness/hooks"], cwd=root, check=True)
            print("git hooks enabled (core.hooksPath=.harness/hooks)")
            return 0
        case "doctor":
            return cmd_doctor(root)
    return 2


if __name__ == "__main__":
    sys.exit(main())
