"""Install and upgrade the harness in a repository; build the vendored single-file CLI."""
from __future__ import annotations

import hashlib
import json
import re
import tomllib
import zipfile
from importlib import resources
from pathlib import Path

from . import adapters, detect, memory, skills
from .core import VENDORED_CLI, VERSION, HarnessError, Report, load_config, load_toml, paths

MANIFEST = ".harness/manifest.toml"
# Configuration merged table by table: new tables and keys are added, existing values are never changed.
MERGE_TOML = {"harness.toml", ".harness/roster.toml"}
# Owned by the project after installation: created when missing, never overwritten.
USER_OWNED = {".harness/architecture.toml", ".harness/exceptions.toml", ".harness/deviations.toml",
              "docs/memory/INDEX.md", "docs/adr/README.md", "docs/changes/.gitkeep"}
ZIP_DATE = (1980, 1, 1, 0, 0, 0)


def _digest(data: bytes, rel: str = "") -> str:
    data = data.replace(b"\r\n", b"\n")
    if rel == "AGENTS.md":  # the generated skills index is not a customization
        data = skills.INDEX_RE.sub(skills.SKILLS_START + "\n" + skills.SKILLS_END, data.decode("utf-8")).encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def _walk(node, prefix: tuple[str, ...] = ()):
    for child in sorted(node.iterdir(), key=lambda c: c.name):
        if child.name == "__pycache__" or child.name.endswith(".pyc"):
            continue
        if child.is_dir():
            yield from _walk(child, prefix + (child.name,))
        else:
            yield "/".join(prefix + (child.name,)), child


def template_files(ci: str) -> dict[str, bytes]:
    """Template content as installed for a CI choice, keyed by repo-relative path (works from a zipapp too)."""
    root = resources.files("sdlc_harness") / "template"
    files = {}
    for rel, node in _walk(root):
        if rel.startswith("ci/"):
            continue
        if ci != "github" and rel.startswith(".github/workflows/"):
            continue
        files[rel] = node.read_bytes()
    if ci == "gitlab":
        files[".gitlab-ci.sdlc.yml"] = (root / "ci" / "gitlab" / ".gitlab-ci.sdlc.yml").read_bytes()
    return files


def build_pyz(target: Path, full: bool = False) -> None:
    """Deterministic stdlib zipapp of the package. `full` also bundles templates so the file can run `init`."""
    package = resources.files("sdlc_harness")
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("wb") as fh:
        fh.write(b"#!/usr/bin/env python3\n")
        with zipfile.ZipFile(fh, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            entries = [("__main__.py", b"import sys\nfrom sdlc_harness.cli import main\nsys.exit(main())\n")]
            entries += [(f"sdlc_harness/{rel}", node.read_bytes()) for rel, node in _walk(package)
                        if full or not rel.startswith("template/")]
            for name, data in sorted(entries):
                info = zipfile.ZipInfo(name, ZIP_DATE)
                info.external_attr = 0o644 << 16
                info.compress_type = zipfile.ZIP_DEFLATED
                zf.writestr(info, data)
    target.chmod(0o755)


def detect_ci(root: Path) -> str:
    if (root / ".gitlab-ci.sdlc.yml").exists():
        return "gitlab"
    return "github" if (root / ".github/workflows/sdlc-gates.yml").exists() else "none"


def _write_manifest(root: Path, files: dict[str, str]) -> None:
    lines = ["# Generated by sdlc init/upgrade: hashes of harness files as installed, used for 3-way upgrades.",
             f"version = {json.dumps(VERSION)}", "", "[files]"]
    lines += [f"{json.dumps(rel)} = {json.dumps(h)}" for rel, h in sorted(files.items())]
    (root / MANIFEST).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _finish(root: Path) -> None:
    build_pyz(root / VENDORED_CLI)
    hooks = root / ".harness" / "hooks"
    for hook in hooks.iterdir() if hooks.is_dir() else []:
        hook.chmod(0o755)


def init(target: Path, profile: str, agents: list[str], mode: str, ci: str | None, adopt: bool = False) -> int:
    target.mkdir(parents=True, exist_ok=True)
    if ci is None:
        ci = "gitlab" if (target / ".gitlab-ci.yml").exists() else "github"
    detected = detect.detect(target) if adopt else None
    skipped, installed = [], {}
    for rel, data in template_files(ci).items():
        dst = target / rel
        if dst.exists():
            skipped.append(rel)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(data)
        installed[rel] = _digest(data, rel)
    _finish(target)

    if "harness.toml" not in skipped:
        cfg_path = target / "harness.toml"
        text = cfg_path.read_text(encoding="utf-8")
        text = re.sub(r'^profile = ".*"$', f'profile = "{profile}"', text, flags=re.M)
        text = re.sub(r"^targets = \[.*\]$", "targets = [" + ", ".join(f'"{a}"' for a in agents) + "]", text, flags=re.M)
        text = re.sub(r'^mode = ".*"$', f'mode = "{mode}"', text, flags=re.M)
        cfg_path.write_text(text, encoding="utf-8")
    if ".harness/roster.toml" not in skipped and ci == "gitlab":
        roster = target / ".harness" / "roster.toml"
        roster.write_text(roster.read_text(encoding="utf-8").replace('platform = "github"', 'platform = "gitlab"'),
                          encoding="utf-8")
    if detected is not None:
        _apply_adoption(target, detected, profile, "AGENTS.md" in skipped)
    _write_manifest(target, installed)

    for s in skipped:
        print(f"skipped existing file: {s}")
    sync(target)
    print(
        "\nNext steps:\n"
        "  1. Edit .harness/roster.toml (people/teams per role), then: python3 .harness/sdlc.pyz codeowners\n"
        "  2. python3 .harness/sdlc.pyz hooks && python3 .harness/sdlc.pyz doctor\n"
        "  3. python3 .harness/sdlc.pyz new feature my-change --risk medium"
    )
    return 0


def _apply_adoption(target: Path, data: dict, profile: str, agents_md_existed: bool) -> None:
    agents_md = target / "AGENTS.md"
    text = agents_md.read_text(encoding="utf-8")
    if not agents_md_existed:
        agents_md.write_text(detect.fill_agents_md(text, data["commands"]), encoding="utf-8")
    elif detect.HARNESS_SECTION_START not in text:
        template = template_files("none")["AGENTS.md"].decode("utf-8")
        agents_md.write_text(text.rstrip() + "\n\n" + detect.harness_block(template), encoding="utf-8")
        print("appended harness sections to existing AGENTS.md")
    if data["contracts"]:
        cfg_path = target / "harness.toml"
        cfg_text = cfg_path.read_text(encoding="utf-8")
        cfg_text = re.sub(r"^(\[contracts\][^\[]*?)^files = \[\]$", lambda m: m.group(1) + f"files = {json.dumps(data['contracts'])}",
                          cfg_text, count=1, flags=re.M | re.S)
        cfg_path.write_text(cfg_text, encoding="utf-8")
    report = target / "docs" / "sdlc" / "adoption.md"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(detect.render_adoption(data, profile), encoding="utf-8")
    print("wrote docs/sdlc/adoption.md")


# --------------------------------------------------------------------------- upgrade

_HEADER_RE = re.compile(r"^\s*\[\[?\s*([^\]]+?)\s*\]\]?\s*(#.*)?$")
_KEY_RE = re.compile(r'^\s*("(?:[^"\\]|\\.)*"|[A-Za-z0-9_-]+)\s*=')


def _blocks(text: str) -> list[tuple[str | None, list[str]]]:
    """Split TOML text into (header path or None for the preamble, lines) blocks."""
    blocks: list[tuple[str | None, list[str]]] = [(None, [])]
    for line in text.splitlines():
        m = _HEADER_RE.match(line)
        if m:
            blocks.append((m.group(1), [line]))
        else:
            blocks[-1][1].append(line)
    return blocks


def _lookup(data: dict, dotted: str):
    node = data
    for part in re.findall(r'"[^"]*"|[^.]+', dotted):
        part = part.strip().strip('"')
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node


def merge_toml(current: str, template: str, label: str) -> tuple[str, list[str]]:
    """Add template tables and keys missing from `current`; never change existing values."""
    cur_data, tpl_data = tomllib.loads(current), tomllib.loads(template)
    notes: list[str] = []
    lines = current.splitlines()
    appended: list[str] = []
    for header, block in _blocks(template):
        if header is None or block[0].lstrip().startswith("[["):
            continue
        existing = _lookup(cur_data, header)
        if existing is None:
            body = list(block)
            while body and not body[-1].strip():
                body.pop()
            appended += ["", *body]
            notes.append(f"{label}: added [{header}]")
            continue
        if not isinstance(existing, dict):
            continue
        tpl_table = _lookup(tpl_data, header) or {}
        missing = [line for line in block[1:] if (m := _KEY_RE.match(line))
                   and m.group(1).strip('"') not in existing
                   and not isinstance(tpl_table.get(m.group(1).strip('"')), dict)]
        if not missing:
            continue
        idx = next(i for i, line in enumerate(lines) if (m := _HEADER_RE.match(line)) and m.group(1) == header)
        end = idx + 1
        while end < len(lines) and not _HEADER_RE.match(lines[end]):
            end += 1
        while end > idx + 1 and not lines[end - 1].strip():
            end -= 1
        for line in missing:
            if line.rstrip().endswith("[") or line.count("[") != line.count("]"):
                notes.append(f"{label}: new multi-line setting in [{header}] needs a manual merge: {line.strip()}")
                continue
            lines.insert(end, line)
            end += 1
            notes.append(f"{label}: added {header}.{_KEY_RE.match(line).group(1)}")
    result = "\n".join(lines + (["", f"# Added by sdlc upgrade {VERSION}"] + appended if appended else [])) + "\n"
    tomllib.loads(result)  # never write invalid TOML
    return result, notes


def upgrade(root: Path, dry_run: bool = False) -> int:
    if not (root / "harness.toml").exists():
        raise HarnessError("harness.toml not found; run `sdlc init` first")
    manifest = load_toml(root / MANIFEST) if (root / MANIFEST).exists() else {}
    base: dict[str, str] = manifest.get("files", {})
    report = Report()
    actions: list[str] = []
    new_manifest: dict[str, str] = {}
    writes: dict[Path, bytes] = {}
    deletes: list[Path] = []

    template = template_files(detect_ci(root))
    for rel, data in template.items():
        path, new_hash = root / rel, _digest(data, rel)
        if rel in MERGE_TOML and path.exists():
            merged, notes = merge_toml(path.read_text(encoding="utf-8"), data.decode("utf-8"), rel)
            if rel == "harness.toml":
                merged = re.sub(r'^version = ".*"$', f'version = "{VERSION}"', merged, count=1, flags=re.M)
            if merged != path.read_text(encoding="utf-8"):
                writes[path] = merged.encode("utf-8")
            actions += notes
            report.warnings += [n for n in notes if "manual merge" in n]
            continue
        if not path.exists():
            if rel in base:
                actions.append(f"kept deleted: {rel} (removed locally)")
                new_manifest[rel] = base[rel]
            else:
                writes[path] = data
                new_manifest[rel] = new_hash
                actions.append(f"added: {rel}")
            continue
        if rel in USER_OWNED:
            continue
        current = _digest(path.read_bytes(), rel)
        if current == new_hash:
            new_manifest[rel] = new_hash
        elif rel in base and current == base[rel]:
            writes[path] = data
            new_manifest[rel] = new_hash
            actions.append(f"updated: {rel}")
        elif rel in base and base[rel] == new_hash:
            new_manifest[rel] = base[rel]
        else:
            writes[path.with_name(path.name + ".sdlc-new")] = data
            if rel in base:
                new_manifest[rel] = base[rel]
            report.warn(f"customized: {rel} - new version written to {rel}.sdlc-new; merge it and delete the .sdlc-new file")

    for rel, old_hash in base.items():
        path = root / rel
        if rel in template or not path.exists():
            continue
        if _digest(path.read_bytes(), rel) == old_hash:
            deletes.append(path)
            actions.append(f"removed obsolete: {rel}")
        else:
            report.warn(f"obsolete but customized: {rel} (no longer shipped; review and delete)")
    legacy = root / ".harness" / "sdlc.py"
    if legacy.exists():
        deletes.append(legacy)
        actions.append("removed legacy: .harness/sdlc.py (replaced by .harness/sdlc.pyz)")

    for a in actions:
        print(a)
    if dry_run:
        print(f"dry run: {len(writes)} write(s), {len(deletes)} deletion(s); nothing changed")
        return report.print()
    for path, data in writes.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    for path in deletes:
        path.unlink()
    _finish(root)
    _write_manifest(root, new_manifest)
    sync(root)
    print(f"upgraded to {manifest.get('version', 'unknown')} -> {VERSION}")
    return report.print()


def sync(root: Path) -> int:
    cfg = load_config(root)
    report, found = skills.check_skills(root, paths(cfg)["skills"])
    if report.errors:
        return report.print()
    if skills.write_index(root, found):
        print("updated AGENTS.md skills index")
    if (root / memory.MEMORY_DIR).is_dir():
        memory.write_index(root)
    adapters.sync(root, cfg)
    return 0
