"""Curated, versioned memory for agents and people: decisions, lessons, conventions, pitfalls.

Entries are Markdown files with frontmatter in `docs/memory/` (project) and `.harness/org/memory/` (organization,
vendored by `sdlc org pull`, read-only). They are reviewed in pull requests like code, which is the main defence
against memory poisoning; `check` also rejects secrets and flags entries past their review date.
"""
from __future__ import annotations

import datetime as dt
import re
import unicodedata
from pathlib import Path

from .core import HarnessError, Report, parse_frontmatter

MEMORY_DIR = "docs/memory"
ORG_MEMORY_DIR = ".harness/org/memory"
INDEX_FILE = "INDEX.md"
TYPES = ["decision", "lesson", "convention", "pitfall", "glossary"]
STATUSES = ["active", "superseded"]
SECRET_PATTERNS = [
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (RSA |EC |OPENSSH |DSA |)PRIVATE KEY-----"),
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b"),
    re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}"),
    re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),
    re.compile(r"(?i)\b(password|passwd|secret|api[_-]?key|token)\s*[:=]\s*['\"]?[^\s'\"]{8,}"),
]
WORD_RE = re.compile(r"[a-z0-9áéíóúñü]+")


def _entries(directory: Path) -> list[dict]:
    out = []
    for f in sorted(directory.glob("*.md")) if directory.is_dir() else []:
        if f.name == INDEX_FILE:
            continue
        parsed = parse_frontmatter(f.read_text(encoding="utf-8"))
        meta, body = parsed if parsed else ({}, f.read_text(encoding="utf-8"))
        tags = [t.strip() for t in meta.get("tags", "").strip("[]").split(",") if t.strip()]
        out.append({**meta, "tags": tags, "body": body, "path": f, "valid_frontmatter": parsed is not None})
    return out


def load(root: Path) -> list[dict]:
    project = [{**e, "origin": "project"} for e in _entries(root / MEMORY_DIR)]
    org = [{**e, "origin": "org"} for e in _entries(root / ORG_MEMORY_DIR)]
    return org + project


def _slug(title: str, limit: int = 60) -> str:
    """ASCII, lowercase, cut on a word boundary: file names travel through tools that mangle accents."""
    folded = unicodedata.normalize("NFKD", title.lower()).encode("ascii", "ignore").decode()
    words, slug = WORD_RE.findall(folded), ""
    for word in words:
        if slug and len(slug) + 1 + len(word) > limit:
            break
        slug = f"{slug}-{word}" if slug else word
    return slug[:limit].strip("-") or "entry"  # a lone word longer than the limit is cut rather than dropped


def add(root: Path, entry_type: str, title: str, tags: list[str], body: str, source: str = "",
        review_days: int = 180) -> Path:
    if entry_type not in TYPES:
        raise HarnessError(f"type must be one of {TYPES}")
    if not title.strip() or not body.strip():
        raise HarnessError("title and body are required")
    for pattern in SECRET_PATTERNS:
        if pattern.search(title + "\n" + body):
            raise HarnessError("memory entry looks like it contains a secret; remove it")
    today = dt.date.today()
    slug = _slug(title)
    directory = root / MEMORY_DIR
    directory.mkdir(parents=True, exist_ok=True)
    entry_id, n = f"MEM-{today.isoformat()}-{slug}", 2
    while (directory / f"{entry_id}.md").exists():
        entry_id, n = f"MEM-{today.isoformat()}-{slug}-{n}", n + 1
    path = directory / f"{entry_id}.md"
    path.write_text(
        "---\n"
        f"id: {entry_id}\n"
        f"type: {entry_type}\n"
        f"title: {title.strip()}\n"
        f"tags: {', '.join(tags)}\n"
        f"source: {source}\n"
        f"created: {today.isoformat()}\n"
        f"review_by: {(today + dt.timedelta(days=review_days)).isoformat()}\n"
        "status: active\n"
        "superseded_by:\n"
        "---\n"
        f"{body.strip()}\n",
        encoding="utf-8",
    )
    write_index(root)
    return path


def search(root: Path, query: str, entry_type: str | None = None, tags: list[str] | None = None,
           limit: int = 5, include_superseded: bool = False) -> list[dict]:
    words = set(WORD_RE.findall(query.lower()))
    results = []
    for e in load(root):
        if entry_type and e.get("type") != entry_type:
            continue
        if tags and not set(tags) & set(e["tags"]):
            continue
        if e.get("status") == "superseded" and not include_superseded:
            continue
        title_words = set(WORD_RE.findall(e.get("title", "").lower()))
        tag_words = {w for t in e["tags"] for w in WORD_RE.findall(t.lower())}
        body_words = WORD_RE.findall(e["body"].lower())
        score = 3 * len(words & title_words) + 3 * len(words & tag_words) + sum(1 for w in body_words if w in words)
        if score or not words:
            results.append({**e, "score": score + (1 if e["origin"] == "org" else 0)})
    return sorted(results, key=lambda e: (-e["score"], e.get("id", "")))[:limit]


def render_index(root: Path) -> str:
    lines = ["# Memory index", "", "Generated by `sdlc memory index`. Read an entry only when its title or tags match "
             "the task. Organization entries (`.harness/org/memory/`) take precedence over project entries.", "",
             "| Id | Type | Title | Tags | Status |", "|---|---|---|---|---|"]
    for e in load(root):
        if e["origin"] != "project":
            continue
        title = e.get("title", "").replace("|", "\\|")
        lines.append(f"| [{e.get('id')}]({e['path'].name}) | {e.get('type')} | {title} | {', '.join(e['tags'])} "
                     f"| {e.get('status')} |")
    return "\n".join(lines) + "\n"


def write_index(root: Path) -> None:
    directory = root / MEMORY_DIR
    directory.mkdir(parents=True, exist_ok=True)
    (directory / INDEX_FILE).write_text(render_index(root), encoding="utf-8")


def check(root: Path) -> Report:
    report = Report()
    entries = load(root)
    ids = {e.get("id") for e in entries}
    today = dt.date.today()
    for e in entries:
        rel = e["path"].relative_to(root)
        if not e["valid_frontmatter"]:
            report.error(f"{rel}: missing frontmatter")
            continue
        if e.get("id") != e["path"].stem:
            report.error(f"{rel}: id must match the file name")
        if e.get("type") not in TYPES:
            report.error(f"{rel}: type must be one of {TYPES}")
        if e.get("status") not in STATUSES:
            report.error(f"{rel}: status must be one of {STATUSES}")
        if e.get("status") == "superseded" and e.get("superseded_by") not in ids:
            report.error(f"{rel}: superseded_by must reference an existing entry")
        if e["origin"] == "project":
            for pattern in SECRET_PATTERNS:
                if pattern.search(e["body"]):
                    report.error(f"{rel}: looks like it contains a secret")
                    break
        try:
            if e.get("status") == "active" and dt.date.fromisoformat(e.get("review_by", "")) < today:
                report.warn(f"{rel}: review date passed; confirm, update or supersede this entry")
        except ValueError:
            report.error(f"{rel}: review_by must be YYYY-MM-DD")
    index = root / MEMORY_DIR / INDEX_FILE
    if any(e["origin"] == "project" for e in entries) and (
            not index.exists() or index.read_text(encoding="utf-8") != render_index(root)):
        report.error(f"{MEMORY_DIR}/{INDEX_FILE} is stale; run `sdlc memory index`")
    return report
