"""Organization policy: mandatory minimums shared across repositories, with time-boxed deviations.

`sdlc org pull` vendors an organization policy repository (or directory) into `.harness/org/` with a lock file of
content hashes, so CI stays offline and local edits are detected. `[require]` entries are enforced (a violation fails
unless a valid deviation exists); `[recommend]` entries only warn. Project settings may be stricter, never looser.
"""
from __future__ import annotations

import datetime as dt
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

from . import authority
from .core import PROFILES, HarnessError, Report, load_toml, sha256_file

ORG_DIR = ".harness/org"
LOCK_FILE = ".harness/org/lock.toml"
DEVIATIONS_FILE = ".harness/deviations.toml"
LEVELS = ["off", "warn", "error"]
SEVERITIES = ["low", "medium", "high", "critical"]


# --------------------------------------------------------------------------- pull

def pull(root: Path, cfg: dict, source: str | None, ref: str | None) -> int:
    org_cfg = cfg.get("organization", {})
    source = source or org_cfg.get("source")
    ref = ref or org_cfg.get("ref", "main")
    if not source:
        raise HarnessError("no organization source: set [organization] source in harness.toml or pass --source")
    with tempfile.TemporaryDirectory() as tmp:
        local = Path(source).expanduser()
        if local.is_dir():
            src, commit = local.resolve(), _git_head(local)
        else:
            src = Path(tmp) / "org"
            proc = subprocess.run(["git", "clone", "--quiet", "--depth", "1", "--branch", ref, source, str(src)],
                                  capture_output=True, text=True)
            if proc.returncode != 0:
                raise HarnessError(f"cannot clone {source}@{ref}: {proc.stderr.strip()}")
            commit = _git_head(src)
        if not (src / "policy.toml").exists():
            raise HarnessError(f"{source} has no policy.toml at its root")
        load_toml(src / "policy.toml")  # fail early on invalid TOML

        target = root / ORG_DIR
        previous = load_toml(root / LOCK_FILE).get("files", {}) if (root / LOCK_FILE).exists() else {}
        for rel in previous:
            (root / rel).unlink(missing_ok=True)
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True)

        files: dict[str, str] = {}
        shutil.copy2(src / "policy.toml", target / "policy.toml")
        files[f"{ORG_DIR}/policy.toml"] = ""
        if (src / "memory").is_dir():
            shutil.copytree(src / "memory", target / "memory")
            files.update({f"{ORG_DIR}/memory/{f.relative_to(src / 'memory').as_posix()}": ""
                          for f in (src / "memory").rglob("*.md")})
        skills_dir = root / cfg.get("paths", {}).get("skills", ".agents/skills")
        for skill in sorted((src / "skills").glob("*/")) if (src / "skills").is_dir() else []:
            if not skill.name.startswith("org-"):
                raise HarnessError(f"organization skill '{skill.name}' must be prefixed 'org-'")
            dst = skills_dir / skill.name
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(skill, dst)
            files.update({(dst / f.relative_to(skill)).relative_to(root).as_posix(): ""
                          for f in skill.rglob("*") if f.is_file()})
        for rel in files:
            files[rel] = sha256_file(root / rel)

    lines = ["# Generated by `sdlc org pull`. Do not edit: change policy in the organization repository.",
             f"source = {json.dumps(source)}", f"ref = {json.dumps(ref)}", f"commit = {json.dumps(commit)}",
             f"pulled_at = {json.dumps(dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat())}",
             "", "[files]"]
    lines += [f"{json.dumps(rel)} = {json.dumps(digest)}" for rel, digest in sorted(files.items())]
    (root / LOCK_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"organization policy {source}@{ref} ({commit[:12]}): {len(files)} file(s) vendored; run `sdlc sync`")
    return 0


def _git_head(path: Path) -> str:
    proc = subprocess.run(["git", "rev-parse", "HEAD"], cwd=path, capture_output=True, text=True)
    return proc.stdout.strip() if proc.returncode == 0 else "local"


# --------------------------------------------------------------------------- evaluation

def _deviations(root: Path, cfg: dict, report: Report) -> dict[str, dict]:
    path = root / DEVIATIONS_FILE
    if not path.exists():
        return {}
    today, valid = dt.date.today(), {}
    allowed_roles = authority.approver_roles(cfg, "deviation")
    for d in load_toml(path).get("deviation", []):
        key = d.get("policy", "?")
        missing = [k for k in ("policy", "reason", "approver", "role", "expires") if not d.get(k)]
        if missing:
            report.error(f"{DEVIATIONS_FILE}: deviation '{key}' lacks {missing}")
            continue
        if d["role"] not in allowed_roles:
            report.error(f"{DEVIATIONS_FILE}: deviation '{key}' role '{d['role']}' may not approve deviations "
                         f"(roster [authority] deviation = {allowed_roles})")
            continue
        if authority.local_membership(cfg, d["role"], d["approver"]) is False:
            report.error(f"{DEVIATIONS_FILE}: '{d['approver']}' is not a member of role '{d['role']}'")
            continue
        expires = d["expires"] if isinstance(d["expires"], dt.date) else dt.date.fromisoformat(str(d["expires"]))
        if expires < today:
            report.error(f"{DEVIATIONS_FILE}: deviation '{key}' expired on {expires}")
            continue
        valid[key] = d
    return valid


def _violations(root: Path, cfg: dict, rules: dict) -> list[tuple[str, str]]:
    """(policy key, message) for every rule the project does not meet."""
    out: list[tuple[str, str]] = []
    harness = cfg.get("harness", {})
    profile = cfg["_profile"]

    if min_profile := rules.get("min_profile"):
        current = harness.get("profile", "standard")
        if current not in PROFILES or PROFILES.index(current) < PROFILES.index(min_profile):
            out.append(("min_profile", f"profile '{current}' is below the organization minimum '{min_profile}'"))

    for name, minimum in rules.get("sensors", {}).items():
        level = profile.get("sensors", {}).get(name, "off")
        if LEVELS.index(level) < LEVELS.index(minimum):
            out.append((f"sensors.{name}", f"sensor '{name}' is '{level}', organization requires at least '{minimum}'"))

    have = set(profile.get("sensors", {}).get("require_evidence", []))
    for kind in rules.get("require_evidence", []):
        if kind not in have:
            out.append((f"require_evidence.{kind}", f"evidence '{kind}' must be required by the profile"))

    deny = set(cfg.get("evidence", {}).get("license_deny", []))
    for lic in rules.get("license_deny", []):
        if lic not in deny:
            out.append((f"license_deny.{lic}", f"license '{lic}' must be in [evidence] license_deny"))

    if max_threshold := rules.get("fail_on_max"):
        current = cfg.get("evidence", {}).get("fail_on", "high")
        if SEVERITIES.index(current) > SEVERITIES.index(max_threshold):
            out.append(("fail_on_max", f"[evidence] fail_on '{current}' is looser than organization '{max_threshold}'"))

    for artifact in rules.get("approvals", []):
        matching = [r for r in profile.get("rules", []) if r["artifact"] == artifact]
        if not matching or not all(r.get("approve") for r in matching):
            out.append((f"approvals.{artifact}", f"every profile rule for '{artifact}' must set approve = true"))

    roster_roles = authority.roles(cfg)
    for role in rules.get("roles_with_members", []):
        if not roster_roles.get(role):
            out.append((f"roles_with_members.{role}", f"roster role '{role}' must have members"))

    if rules.get("separation_of_duties") and not authority.settings(cfg)["separation_of_duties"]:
        out.append(("separation_of_duties", "roster settings.separation_of_duties must be true"))

    if rules.get("require_ci") and not ((root / ".github/workflows/sdlc-gates.yml").exists()
                                        or (root / ".gitlab-ci.sdlc.yml").exists()):
        out.append(("require_ci", "the sdlc CI gate must be installed"))

    agents_md = (root / "AGENTS.md").read_text(encoding="utf-8") if (root / "AGENTS.md").exists() else ""
    for i, line in enumerate(rules.get("agents_md_lines", [])):
        if line not in agents_md:
            out.append((f"agents_md_lines.{i}", f"AGENTS.md must contain the organization rule: {line!r}"))
    return out


def check(root: Path, cfg: dict) -> Report:
    report = Report()
    lock_path = root / LOCK_FILE
    if not lock_path.exists():
        if cfg.get("organization", {}).get("source"):
            report.error("organization source configured but policy not vendored; run `sdlc org pull`")
        return report
    lock = load_toml(lock_path)
    for rel, digest in lock.get("files", {}).items():
        path = root / rel
        if not path.exists():
            report.error(f"{rel}: organization file missing; run `sdlc org pull`")
        elif sha256_file(path) != digest:
            report.error(f"{rel}: modified locally; change it in the organization repository ({lock.get('source')})")
    policy_path = root / ORG_DIR / "policy.toml"
    if not policy_path.exists():
        return report
    policy = load_toml(policy_path)
    label = f"{policy.get('policy', {}).get('id', 'organization')}@{policy.get('policy', {}).get('version', '?')}"
    deviations = _deviations(root, cfg, report)
    for key, message in _violations(root, cfg, policy.get("require", {})):
        if key in deviations:
            d = deviations[key]
            report.warn(f"policy {label}: {message} - deviation until {d['expires']} by {d['approver']}: {d['reason']}")
        else:
            report.error(f"policy {label}: {message}")
    for key, message in _violations(root, cfg, policy.get("recommend", {})):
        report.warn(f"policy {label} (recommended): {message}")
    for key in deviations:
        if key not in {k for k, _ in _violations(root, cfg, policy.get("require", {}))}:
            report.warn(f"{DEVIATIONS_FILE}: deviation '{key}' is no longer needed; remove it")
    return report
